version: '3'

services:
  db:
    image: postgres:10.14-alpine
    restart: always
    # [localhost port]:[default service port in docker]
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres_test'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - database-data:/var/lib/postgresql/data
  springapp:
    build: .
    container_name: dashboard
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres_test
    # [localhost port]:[default service port in docker]
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db

volumes:
  database-data: # named volumes can be managed easier using docker-compose